version: 2
jobs:
  build:
    docker:
      - image: quarkchaindocker/goquarkchain

    working_directory: /go/src/github.com/QuarkChain/goquarkchain


    steps:
      - run: pwd
      - checkout

      - restore_cache:
          keys:
            - go-mod-v2-{{ checksum "go.sum" }}

      # Build qkchash c++
      - run: cd consensus/qkchash/native && make && cd -
      - run: go vet ./...
      - run: pwd
      - save_cache:
          key: go-mod-v2-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
  test:
    docker:
      - image: quarkchaindocker/goquarkchain
    working_directory: /go/src/github.com/QuarkChain/goquarkchain

    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v2-{{checksum "go.sum"}}
      - run: cd consensus/qkchash/native && make && cd -
      - run: go vet ./...
      - run: go test -timeout 1m ./... -gcflags=-l
      - save_cache:
          key: go-mod-v2-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"


  check-db:
    docker:
      - image: quarkchaindocker/goquarkchain

    working_directory: /go/src/github.com/QuarkChain/goquarkchain

    steps:
      - checkout:
      - restore_cache:
          keys:
            - go-mod-v2-{{ checksum "go.sum" }}

      - run:
          name: check remote stats
          command: |
            apt-get install sshpass
            ls
            sshpass -p 'goquarkchain' scp root@138.68.224.79:/root/master.log ./
            pwd
            ls
            cat master.log




workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - check-db:
          requires:
            - build
  nightly:
    triggers:
      - schedule:
          cron: "0 3 * * *"
          filters:
            branches:
              only:
                - dev
    jobs:
      - build
      - download-snapshot
      - check-db:
          requires:
            - build
            - download-snapshot
