version: 2
jobs:
  build:
    docker:
      - image: quarkchaindocker/goquarkchain

    working_directory: /go/src/github.com/QuarkChain/goquarkchain


    steps:
      - run: pwd
      - checkout

      - restore_cache:
          keys:
            - go-mod-v2-{{ checksum "go.sum" }}

      # Build qkchash c++
      - run: cd consensus/qkchash/native && make && cd -
      - run: go vet ./...
      - run: pwd
      - save_cache:
          key: go-mod-v2-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
  test:
    docker:
      - image: quarkchaindocker/goquarkchain
    working_directory: /go/src/github.com/QuarkChain/goquarkchain

    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v2-{{checksum "go.sum"}}
      - run: cd consensus/qkchash/native && make && cd -
      - run: go vet ./...
      - run: go test -timeout 1m ./... -gcflags=-l
      - save_cache:
          key: go-mod-v2-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"


  check-db:
    docker:
      - image: quarkchaindocker/goquarkchain

    working_directory: /go/src/github.com/QuarkChain/goquarkchain

    steps:
      - checkout:
      - restore_cache:
          keys:
            - go-mod-v2-{{ checksum "go.sum" }}

      - run:
          name: check remote stats
          command: |
            apt-get update && apt-get install sshpass
            ssh-keygen -R 167.71.117.195
            echo $CheckDBHostPassword
            sshpass -p $CheckDBHostPassword scp -o StrictHostKeyChecking=no root@167.71.117.195:/tmp/status.txt ./
            cat status.log




workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - check-db:
          requires:
            - build
  nightly:
    triggers:
      - schedule:
          cron: "*/5 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
      - check-db:
          requires:
            - build
